//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ObjC.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IObjCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class ObjCBaseListener : IObjCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.synchronized_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSynchronized_statement([NotNull] ObjCParser.Synchronized_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.synchronized_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSynchronized_statement([NotNull] ObjCParser.Synchronized_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.try_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTry_statement([NotNull] ObjCParser.Try_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.try_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTry_statement([NotNull] ObjCParser.Try_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator([NotNull] ObjCParser.DeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator([NotNull] ObjCParser.DeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.autorelease_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAutorelease_statement([NotNull] ObjCParser.Autorelease_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.autorelease_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAutorelease_statement([NotNull] ObjCParser.Autorelease_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_implementation([NotNull] ObjCParser.Property_implementationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_implementation([NotNull] ObjCParser.Property_implementationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.receiver"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReceiver([NotNull] ObjCParser.ReceiverContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.receiver"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReceiver([NotNull] ObjCParser.ReceiverContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.labeled_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabeled_statement([NotNull] ObjCParser.Labeled_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.labeled_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabeled_statement([NotNull] ObjCParser.Labeled_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.message_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage_expression([NotNull] ObjCParser.Message_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.message_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage_expression([NotNull] ObjCParser.Message_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_statement([NotNull] ObjCParser.Compound_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_statement([NotNull] ObjCParser.Compound_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.box_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBox_expression([NotNull] ObjCParser.Box_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.box_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBox_expression([NotNull] ObjCParser.Box_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.arc_behaviour_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArc_behaviour_specifier([NotNull] ObjCParser.Arc_behaviour_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.arc_behaviour_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArc_behaviour_specifier([NotNull] ObjCParser.Arc_behaviour_specifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCast_expression([NotNull] ObjCParser.Cast_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCast_expression([NotNull] ObjCParser.Cast_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality_expression([NotNull] ObjCParser.Equality_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality_expression([NotNull] ObjCParser.Equality_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_statement([NotNull] ObjCParser.For_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_statement([NotNull] ObjCParser.For_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.storage_class_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorage_class_specifier([NotNull] ObjCParser.Storage_class_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.storage_class_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorage_class_specifier([NotNull] ObjCParser.Storage_class_specifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_interface([NotNull] ObjCParser.Class_interfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_interface([NotNull] ObjCParser.Class_interfaceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_definition([NotNull] ObjCParser.Function_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_definition([NotNull] ObjCParser.Function_definitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.block_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock_parameters([NotNull] ObjCParser.Block_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.block_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock_parameters([NotNull] ObjCParser.Block_parametersContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.array_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_expression([NotNull] ObjCParser.Array_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.array_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_expression([NotNull] ObjCParser.Array_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslation_unit([NotNull] ObjCParser.Translation_unitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslation_unit([NotNull] ObjCParser.Translation_unitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_qualifier([NotNull] ObjCParser.Type_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_qualifier([NotNull] ObjCParser.Type_qualifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_list([NotNull] ObjCParser.Protocol_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_list([NotNull] ObjCParser.Protocol_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.logical_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_and_expression([NotNull] ObjCParser.Logical_and_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.logical_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_and_expression([NotNull] ObjCParser.Logical_and_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expression([NotNull] ObjCParser.Shift_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expression([NotNull] ObjCParser.Shift_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_declaration([NotNull] ObjCParser.Method_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_declaration([NotNull] ObjCParser.Method_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_name([NotNull] ObjCParser.Type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_name([NotNull] ObjCParser.Type_nameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer([NotNull] ObjCParser.PointerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer([NotNull] ObjCParser.PointerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_definition([NotNull] ObjCParser.Method_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_definition([NotNull] ObjCParser.Method_definitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_list([NotNull] ObjCParser.Parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_list([NotNull] ObjCParser.Parameter_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.encode_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncode_expression([NotNull] ObjCParser.Encode_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.encode_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncode_expression([NotNull] ObjCParser.Encode_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusive_or_expression([NotNull] ObjCParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusive_or_expression([NotNull] ObjCParser.Inclusive_or_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant_expression([NotNull] ObjCParser.Constant_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant_expression([NotNull] ObjCParser.Constant_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.dictionary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictionary_expression([NotNull] ObjCParser.Dictionary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.dictionary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictionary_expression([NotNull] ObjCParser.Dictionary_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelational_expression([NotNull] ObjCParser.Relational_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelational_expression([NotNull] ObjCParser.Relational_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_name([NotNull] ObjCParser.Class_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_name([NotNull] ObjCParser.Class_nameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declaration_specifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration_specifiers([NotNull] ObjCParser.Declaration_specifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declaration_specifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration_specifiers([NotNull] ObjCParser.Declaration_specifiersContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.parameter_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_declaration_list([NotNull] ObjCParser.Parameter_declaration_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.parameter_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_declaration_list([NotNull] ObjCParser.Parameter_declaration_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_expression([NotNull] ObjCParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_expression([NotNull] ObjCParser.Postfix_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.keyword_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword_declarator([NotNull] ObjCParser.Keyword_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.keyword_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword_declarator([NotNull] ObjCParser.Keyword_declaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.message_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage_selector([NotNull] ObjCParser.Message_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.message_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage_selector([NotNull] ObjCParser.Message_selectorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_declaration([NotNull] ObjCParser.Property_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_declaration([NotNull] ObjCParser.Property_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.preprocessor_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessor_declaration([NotNull] ObjCParser.Preprocessor_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.preprocessor_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessor_declaration([NotNull] ObjCParser.Preprocessor_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_attributes_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_attributes_declaration([NotNull] ObjCParser.Property_attributes_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_attributes_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_attributes_declaration([NotNull] ObjCParser.Property_attributes_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selection_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection_statement([NotNull] ObjCParser.Selection_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selection_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection_statement([NotNull] ObjCParser.Selection_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_variable_declarator([NotNull] ObjCParser.Type_variable_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_variable_declarator([NotNull] ObjCParser.Type_variable_declaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_reference_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_reference_list([NotNull] ObjCParser.Protocol_reference_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_reference_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_reference_list([NotNull] ObjCParser.Protocol_reference_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.finally_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinally_statement([NotNull] ObjCParser.Finally_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.finally_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinally_statement([NotNull] ObjCParser.Finally_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.try_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTry_block([NotNull] ObjCParser.Try_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.try_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTry_block([NotNull] ObjCParser.Try_blockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_method_definition([NotNull] ObjCParser.Class_method_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_method_definition([NotNull] ObjCParser.Class_method_definitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_declaration_list([NotNull] ObjCParser.Protocol_declaration_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_declaration_list([NotNull] ObjCParser.Protocol_declaration_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_synthesize_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_synthesize_list([NotNull] ObjCParser.Property_synthesize_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_synthesize_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_synthesize_list([NotNull] ObjCParser.Property_synthesize_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.block_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock_type([NotNull] ObjCParser.Block_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.block_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock_type([NotNull] ObjCParser.Block_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_expression([NotNull] ObjCParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_expression([NotNull] ObjCParser.Conditional_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_declaration_list([NotNull] ObjCParser.Class_declaration_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_declaration_list([NotNull] ObjCParser.Class_declaration_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression([NotNull] ObjCParser.Primary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression([NotNull] ObjCParser.Primary_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.keyword_argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword_argument([NotNull] ObjCParser.Keyword_argumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.keyword_argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword_argument([NotNull] ObjCParser.Keyword_argumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.specifier_qualifier_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecifier_qualifier_list([NotNull] ObjCParser.Specifier_qualifier_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.specifier_qualifier_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecifier_qualifier_list([NotNull] ObjCParser.Specifier_qualifier_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.visibility_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility_specification([NotNull] ObjCParser.Visibility_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.visibility_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility_specification([NotNull] ObjCParser.Visibility_specificationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.category_interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCategory_interface([NotNull] ObjCParser.Category_interfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.category_interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCategory_interface([NotNull] ObjCParser.Category_interfaceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer([NotNull] ObjCParser.InitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer([NotNull] ObjCParser.InitializerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ObjCParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ObjCParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] ObjCParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] ObjCParser.SelectorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_declaration([NotNull] ObjCParser.Protocol_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_declaration([NotNull] ObjCParser.Protocol_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_attributes_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_attributes_list([NotNull] ObjCParser.Property_attributes_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_attributes_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_attributes_list([NotNull] ObjCParser.Property_attributes_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_expression([NotNull] ObjCParser.Assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_expression([NotNull] ObjCParser.Assignment_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicative_expression([NotNull] ObjCParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicative_expression([NotNull] ObjCParser.Multiplicative_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_attribute([NotNull] ObjCParser.Property_attributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_attribute([NotNull] ObjCParser.Property_attributeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump_statement([NotNull] ObjCParser.Jump_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump_statement([NotNull] ObjCParser.Jump_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.instance_method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstance_method_definition([NotNull] ObjCParser.Instance_method_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.instance_method_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstance_method_definition([NotNull] ObjCParser.Instance_method_definitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.enumerator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerator([NotNull] ObjCParser.EnumeratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.enumerator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerator([NotNull] ObjCParser.EnumeratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_qualifier([NotNull] ObjCParser.Protocol_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_qualifier([NotNull] ObjCParser.Protocol_qualifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declarator_list([NotNull] ObjCParser.Struct_declarator_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declarator_list([NotNull] ObjCParser.Struct_declarator_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.interface_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_declaration_list([NotNull] ObjCParser.Interface_declaration_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.interface_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_declaration_list([NotNull] ObjCParser.Interface_declaration_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declarator([NotNull] ObjCParser.Struct_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declarator([NotNull] ObjCParser.Struct_declaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_expression([NotNull] ObjCParser.Protocol_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_expression([NotNull] ObjCParser.Protocol_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_method_declaration([NotNull] ObjCParser.Class_method_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_method_declaration([NotNull] ObjCParser.Class_method_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selector_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector_name([NotNull] ObjCParser.Selector_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selector_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector_name([NotNull] ObjCParser.Selector_nameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] ObjCParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] ObjCParser.DeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.init_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit_declarator_list([NotNull] ObjCParser.Init_declarator_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.init_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit_declarator_list([NotNull] ObjCParser.Init_declarator_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.init_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit_declarator([NotNull] ObjCParser.Init_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.init_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit_declarator([NotNull] ObjCParser.Init_declaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_or_union_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_or_union_specifier([NotNull] ObjCParser.Struct_or_union_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_or_union_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_or_union_specifier([NotNull] ObjCParser.Struct_or_union_specifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.do_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDo_statement([NotNull] ObjCParser.Do_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.do_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDo_statement([NotNull] ObjCParser.Do_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusive_or_expression([NotNull] ObjCParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusive_or_expression([NotNull] ObjCParser.Exclusive_or_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.enumerator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerator_list([NotNull] ObjCParser.Enumerator_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.enumerator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerator_list([NotNull] ObjCParser.Enumerator_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ObjCParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ObjCParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditive_expression([NotNull] ObjCParser.Additive_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditive_expression([NotNull] ObjCParser.Additive_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_operator([NotNull] ObjCParser.Unary_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_operator([NotNull] ObjCParser.Unary_operatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.category_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCategory_name([NotNull] ObjCParser.Category_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.category_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCategory_name([NotNull] ObjCParser.Category_nameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.instance_variables"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstance_variables([NotNull] ObjCParser.Instance_variablesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.instance_variables"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstance_variables([NotNull] ObjCParser.Instance_variablesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.logical_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_or_expression([NotNull] ObjCParser.Logical_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.logical_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_or_expression([NotNull] ObjCParser.Logical_or_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.iteration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIteration_statement([NotNull] ObjCParser.Iteration_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.iteration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIteration_statement([NotNull] ObjCParser.Iteration_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.throw_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrow_statement([NotNull] ObjCParser.Throw_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.throw_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrow_statement([NotNull] ObjCParser.Throw_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] ObjCParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] ObjCParser.IdentifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.argument_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_expression_list([NotNull] ObjCParser.Argument_expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.argument_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_expression_list([NotNull] ObjCParser.Argument_expression_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_implementation([NotNull] ObjCParser.Class_implementationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_implementation([NotNull] ObjCParser.Class_implementationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] ObjCParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] ObjCParser.While_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declaration([NotNull] ObjCParser.Struct_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declaration([NotNull] ObjCParser.Struct_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.enum_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_specifier([NotNull] ObjCParser.Enum_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.enum_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_specifier([NotNull] ObjCParser.Enum_specifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.parameter_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_declaration([NotNull] ObjCParser.Parameter_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.parameter_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_declaration([NotNull] ObjCParser.Parameter_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_selector([NotNull] ObjCParser.Method_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_selector([NotNull] ObjCParser.Method_selectorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] ObjCParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] ObjCParser.Assignment_operatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] ObjCParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] ObjCParser.Unary_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.instance_method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstance_method_declaration([NotNull] ObjCParser.Instance_method_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.instance_method_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstance_method_declaration([NotNull] ObjCParser.Instance_method_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_type([NotNull] ObjCParser.Method_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_type([NotNull] ObjCParser.Method_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocol_name([NotNull] ObjCParser.Protocol_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocol_name([NotNull] ObjCParser.Protocol_nameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.for_in_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_in_statement([NotNull] ObjCParser.For_in_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.for_in_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_in_statement([NotNull] ObjCParser.For_in_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.category_implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCategory_implementation([NotNull] ObjCParser.Category_implementationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.category_implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCategory_implementation([NotNull] ObjCParser.Category_implementationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] ObjCParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] ObjCParser.ConstantContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_list([NotNull] ObjCParser.Statement_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_list([NotNull] ObjCParser.Statement_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.abstract_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbstract_declarator([NotNull] ObjCParser.Abstract_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.abstract_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbstract_declarator([NotNull] ObjCParser.Abstract_declaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.external_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternal_declaration([NotNull] ObjCParser.External_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.external_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternal_declaration([NotNull] ObjCParser.External_declarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.block_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock_expression([NotNull] ObjCParser.Block_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.block_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock_expression([NotNull] ObjCParser.Block_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.abstract_declarator_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbstract_declarator_suffix([NotNull] ObjCParser.Abstract_declarator_suffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.abstract_declarator_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbstract_declarator_suffix([NotNull] ObjCParser.Abstract_declarator_suffixContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_list([NotNull] ObjCParser.Class_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_list([NotNull] ObjCParser.Class_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_synthesize_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_synthesize_item([NotNull] ObjCParser.Property_synthesize_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_synthesize_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_synthesize_item([NotNull] ObjCParser.Property_synthesize_itemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.direct_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirect_declarator([NotNull] ObjCParser.Direct_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.direct_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirect_declarator([NotNull] ObjCParser.Direct_declaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.implementation_definition_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementation_definition_list([NotNull] ObjCParser.Implementation_definition_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.implementation_definition_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementation_definition_list([NotNull] ObjCParser.Implementation_definition_listContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expression([NotNull] ObjCParser.And_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expression([NotNull] ObjCParser.And_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.superclass_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperclass_name([NotNull] ObjCParser.Superclass_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.superclass_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperclass_name([NotNull] ObjCParser.Superclass_nameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.catch_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatch_statement([NotNull] ObjCParser.Catch_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.catch_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatch_statement([NotNull] ObjCParser.Catch_statementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.dictionary_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictionary_pair([NotNull] ObjCParser.Dictionary_pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.dictionary_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictionary_pair([NotNull] ObjCParser.Dictionary_pairContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_specifier([NotNull] ObjCParser.Type_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_specifier([NotNull] ObjCParser.Type_specifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selector_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector_expression([NotNull] ObjCParser.Selector_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selector_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector_expression([NotNull] ObjCParser.Selector_expressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declarator_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator_suffix([NotNull] ObjCParser.Declarator_suffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declarator_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator_suffix([NotNull] ObjCParser.Declarator_suffixContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
