//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ObjC.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ObjCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IObjCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.synchronized_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSynchronized_statement([NotNull] ObjCParser.Synchronized_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.synchronized_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSynchronized_statement([NotNull] ObjCParser.Synchronized_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_statement([NotNull] ObjCParser.Try_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_statement([NotNull] ObjCParser.Try_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] ObjCParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] ObjCParser.DeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.autorelease_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAutorelease_statement([NotNull] ObjCParser.Autorelease_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.autorelease_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAutorelease_statement([NotNull] ObjCParser.Autorelease_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_implementation([NotNull] ObjCParser.Property_implementationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_implementation([NotNull] ObjCParser.Property_implementationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.receiver"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReceiver([NotNull] ObjCParser.ReceiverContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.receiver"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReceiver([NotNull] ObjCParser.ReceiverContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.labeled_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeled_statement([NotNull] ObjCParser.Labeled_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.labeled_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeled_statement([NotNull] ObjCParser.Labeled_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.message_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage_expression([NotNull] ObjCParser.Message_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.message_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage_expression([NotNull] ObjCParser.Message_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_statement([NotNull] ObjCParser.Compound_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_statement([NotNull] ObjCParser.Compound_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.box_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBox_expression([NotNull] ObjCParser.Box_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.box_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBox_expression([NotNull] ObjCParser.Box_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.arc_behaviour_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArc_behaviour_specifier([NotNull] ObjCParser.Arc_behaviour_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.arc_behaviour_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArc_behaviour_specifier([NotNull] ObjCParser.Arc_behaviour_specifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCast_expression([NotNull] ObjCParser.Cast_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCast_expression([NotNull] ObjCParser.Cast_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality_expression([NotNull] ObjCParser.Equality_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality_expression([NotNull] ObjCParser.Equality_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_statement([NotNull] ObjCParser.For_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_statement([NotNull] ObjCParser.For_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.storage_class_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorage_class_specifier([NotNull] ObjCParser.Storage_class_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.storage_class_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorage_class_specifier([NotNull] ObjCParser.Storage_class_specifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_interface([NotNull] ObjCParser.Class_interfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_interface([NotNull] ObjCParser.Class_interfaceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_definition([NotNull] ObjCParser.Function_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_definition([NotNull] ObjCParser.Function_definitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.block_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock_parameters([NotNull] ObjCParser.Block_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.block_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock_parameters([NotNull] ObjCParser.Block_parametersContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.array_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_expression([NotNull] ObjCParser.Array_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.array_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_expression([NotNull] ObjCParser.Array_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslation_unit([NotNull] ObjCParser.Translation_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslation_unit([NotNull] ObjCParser.Translation_unitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_qualifier([NotNull] ObjCParser.Type_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_qualifier([NotNull] ObjCParser.Type_qualifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_list([NotNull] ObjCParser.Protocol_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_list([NotNull] ObjCParser.Protocol_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.logical_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_and_expression([NotNull] ObjCParser.Logical_and_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.logical_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_and_expression([NotNull] ObjCParser.Logical_and_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expression([NotNull] ObjCParser.Shift_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expression([NotNull] ObjCParser.Shift_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_declaration([NotNull] ObjCParser.Method_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_declaration([NotNull] ObjCParser.Method_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] ObjCParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] ObjCParser.Type_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer([NotNull] ObjCParser.PointerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer([NotNull] ObjCParser.PointerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_definition([NotNull] ObjCParser.Method_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_definition([NotNull] ObjCParser.Method_definitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_list([NotNull] ObjCParser.Parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_list([NotNull] ObjCParser.Parameter_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.encode_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncode_expression([NotNull] ObjCParser.Encode_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.encode_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncode_expression([NotNull] ObjCParser.Encode_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusive_or_expression([NotNull] ObjCParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusive_or_expression([NotNull] ObjCParser.Inclusive_or_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_expression([NotNull] ObjCParser.Constant_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_expression([NotNull] ObjCParser.Constant_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.dictionary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionary_expression([NotNull] ObjCParser.Dictionary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.dictionary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionary_expression([NotNull] ObjCParser.Dictionary_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelational_expression([NotNull] ObjCParser.Relational_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelational_expression([NotNull] ObjCParser.Relational_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_name([NotNull] ObjCParser.Class_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_name([NotNull] ObjCParser.Class_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declaration_specifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration_specifiers([NotNull] ObjCParser.Declaration_specifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declaration_specifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration_specifiers([NotNull] ObjCParser.Declaration_specifiersContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.parameter_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_declaration_list([NotNull] ObjCParser.Parameter_declaration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.parameter_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_declaration_list([NotNull] ObjCParser.Parameter_declaration_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_expression([NotNull] ObjCParser.Postfix_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_expression([NotNull] ObjCParser.Postfix_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.keyword_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_declarator([NotNull] ObjCParser.Keyword_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.keyword_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_declarator([NotNull] ObjCParser.Keyword_declaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.message_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage_selector([NotNull] ObjCParser.Message_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.message_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage_selector([NotNull] ObjCParser.Message_selectorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_declaration([NotNull] ObjCParser.Property_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_declaration([NotNull] ObjCParser.Property_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.preprocessor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreprocessor_declaration([NotNull] ObjCParser.Preprocessor_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.preprocessor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreprocessor_declaration([NotNull] ObjCParser.Preprocessor_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_attributes_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_attributes_declaration([NotNull] ObjCParser.Property_attributes_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_attributes_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_attributes_declaration([NotNull] ObjCParser.Property_attributes_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection_statement([NotNull] ObjCParser.Selection_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection_statement([NotNull] ObjCParser.Selection_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_variable_declarator([NotNull] ObjCParser.Type_variable_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_variable_declarator([NotNull] ObjCParser.Type_variable_declaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_reference_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_reference_list([NotNull] ObjCParser.Protocol_reference_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_reference_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_reference_list([NotNull] ObjCParser.Protocol_reference_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.finally_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinally_statement([NotNull] ObjCParser.Finally_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.finally_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinally_statement([NotNull] ObjCParser.Finally_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.try_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_block([NotNull] ObjCParser.Try_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.try_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_block([NotNull] ObjCParser.Try_blockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_method_definition([NotNull] ObjCParser.Class_method_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_method_definition([NotNull] ObjCParser.Class_method_definitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_declaration_list([NotNull] ObjCParser.Protocol_declaration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_declaration_list([NotNull] ObjCParser.Protocol_declaration_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_synthesize_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_synthesize_list([NotNull] ObjCParser.Property_synthesize_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_synthesize_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_synthesize_list([NotNull] ObjCParser.Property_synthesize_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.block_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock_type([NotNull] ObjCParser.Block_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.block_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock_type([NotNull] ObjCParser.Block_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_expression([NotNull] ObjCParser.Conditional_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_expression([NotNull] ObjCParser.Conditional_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_declaration_list([NotNull] ObjCParser.Class_declaration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_declaration_list([NotNull] ObjCParser.Class_declaration_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_expression([NotNull] ObjCParser.Primary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_expression([NotNull] ObjCParser.Primary_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.keyword_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_argument([NotNull] ObjCParser.Keyword_argumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.keyword_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_argument([NotNull] ObjCParser.Keyword_argumentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.specifier_qualifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecifier_qualifier_list([NotNull] ObjCParser.Specifier_qualifier_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.specifier_qualifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecifier_qualifier_list([NotNull] ObjCParser.Specifier_qualifier_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.visibility_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility_specification([NotNull] ObjCParser.Visibility_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.visibility_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility_specification([NotNull] ObjCParser.Visibility_specificationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.category_interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCategory_interface([NotNull] ObjCParser.Category_interfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.category_interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCategory_interface([NotNull] ObjCParser.Category_interfaceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] ObjCParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] ObjCParser.InitializerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ObjCParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ObjCParser.ExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] ObjCParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] ObjCParser.SelectorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_declaration([NotNull] ObjCParser.Protocol_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_declaration([NotNull] ObjCParser.Protocol_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_attributes_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_attributes_list([NotNull] ObjCParser.Property_attributes_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_attributes_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_attributes_list([NotNull] ObjCParser.Property_attributes_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_expression([NotNull] ObjCParser.Assignment_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_expression([NotNull] ObjCParser.Assignment_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicative_expression([NotNull] ObjCParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicative_expression([NotNull] ObjCParser.Multiplicative_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_attribute([NotNull] ObjCParser.Property_attributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_attribute([NotNull] ObjCParser.Property_attributeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump_statement([NotNull] ObjCParser.Jump_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump_statement([NotNull] ObjCParser.Jump_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.instance_method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstance_method_definition([NotNull] ObjCParser.Instance_method_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.instance_method_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstance_method_definition([NotNull] ObjCParser.Instance_method_definitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator([NotNull] ObjCParser.EnumeratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator([NotNull] ObjCParser.EnumeratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_qualifier([NotNull] ObjCParser.Protocol_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_qualifier([NotNull] ObjCParser.Protocol_qualifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declarator_list([NotNull] ObjCParser.Struct_declarator_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declarator_list([NotNull] ObjCParser.Struct_declarator_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.interface_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface_declaration_list([NotNull] ObjCParser.Interface_declaration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.interface_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface_declaration_list([NotNull] ObjCParser.Interface_declaration_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declarator([NotNull] ObjCParser.Struct_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declarator([NotNull] ObjCParser.Struct_declaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_expression([NotNull] ObjCParser.Protocol_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_expression([NotNull] ObjCParser.Protocol_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_method_declaration([NotNull] ObjCParser.Class_method_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_method_declaration([NotNull] ObjCParser.Class_method_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selector_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector_name([NotNull] ObjCParser.Selector_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selector_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector_name([NotNull] ObjCParser.Selector_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] ObjCParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] ObjCParser.DeclarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit_declarator_list([NotNull] ObjCParser.Init_declarator_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit_declarator_list([NotNull] ObjCParser.Init_declarator_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.init_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit_declarator([NotNull] ObjCParser.Init_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.init_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit_declarator([NotNull] ObjCParser.Init_declaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_or_union_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_or_union_specifier([NotNull] ObjCParser.Struct_or_union_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_or_union_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_or_union_specifier([NotNull] ObjCParser.Struct_or_union_specifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.do_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDo_statement([NotNull] ObjCParser.Do_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.do_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDo_statement([NotNull] ObjCParser.Do_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusive_or_expression([NotNull] ObjCParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusive_or_expression([NotNull] ObjCParser.Exclusive_or_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.enumerator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator_list([NotNull] ObjCParser.Enumerator_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.enumerator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator_list([NotNull] ObjCParser.Enumerator_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ObjCParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ObjCParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditive_expression([NotNull] ObjCParser.Additive_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditive_expression([NotNull] ObjCParser.Additive_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator([NotNull] ObjCParser.Unary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator([NotNull] ObjCParser.Unary_operatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.category_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCategory_name([NotNull] ObjCParser.Category_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.category_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCategory_name([NotNull] ObjCParser.Category_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.instance_variables"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstance_variables([NotNull] ObjCParser.Instance_variablesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.instance_variables"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstance_variables([NotNull] ObjCParser.Instance_variablesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.logical_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_or_expression([NotNull] ObjCParser.Logical_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.logical_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_or_expression([NotNull] ObjCParser.Logical_or_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIteration_statement([NotNull] ObjCParser.Iteration_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIteration_statement([NotNull] ObjCParser.Iteration_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrow_statement([NotNull] ObjCParser.Throw_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrow_statement([NotNull] ObjCParser.Throw_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] ObjCParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] ObjCParser.IdentifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.argument_expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_expression_list([NotNull] ObjCParser.Argument_expression_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.argument_expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_expression_list([NotNull] ObjCParser.Argument_expression_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_implementation([NotNull] ObjCParser.Class_implementationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_implementation([NotNull] ObjCParser.Class_implementationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_statement([NotNull] ObjCParser.While_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_statement([NotNull] ObjCParser.While_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declaration([NotNull] ObjCParser.Struct_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declaration([NotNull] ObjCParser.Struct_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.enum_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_specifier([NotNull] ObjCParser.Enum_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.enum_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_specifier([NotNull] ObjCParser.Enum_specifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_declaration([NotNull] ObjCParser.Parameter_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_declaration([NotNull] ObjCParser.Parameter_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_selector([NotNull] ObjCParser.Method_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_selector([NotNull] ObjCParser.Method_selectorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] ObjCParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] ObjCParser.Assignment_operatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expression([NotNull] ObjCParser.Unary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expression([NotNull] ObjCParser.Unary_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.instance_method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstance_method_declaration([NotNull] ObjCParser.Instance_method_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.instance_method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstance_method_declaration([NotNull] ObjCParser.Instance_method_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.method_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_type([NotNull] ObjCParser.Method_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.method_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_type([NotNull] ObjCParser.Method_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.protocol_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_name([NotNull] ObjCParser.Protocol_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.protocol_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_name([NotNull] ObjCParser.Protocol_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.for_in_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_in_statement([NotNull] ObjCParser.For_in_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.for_in_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_in_statement([NotNull] ObjCParser.For_in_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.category_implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCategory_implementation([NotNull] ObjCParser.Category_implementationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.category_implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCategory_implementation([NotNull] ObjCParser.Category_implementationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] ObjCParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] ObjCParser.ConstantContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_list([NotNull] ObjCParser.Statement_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_list([NotNull] ObjCParser.Statement_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.abstract_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstract_declarator([NotNull] ObjCParser.Abstract_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.abstract_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstract_declarator([NotNull] ObjCParser.Abstract_declaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternal_declaration([NotNull] ObjCParser.External_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternal_declaration([NotNull] ObjCParser.External_declarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.block_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock_expression([NotNull] ObjCParser.Block_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.block_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock_expression([NotNull] ObjCParser.Block_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.abstract_declarator_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstract_declarator_suffix([NotNull] ObjCParser.Abstract_declarator_suffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.abstract_declarator_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstract_declarator_suffix([NotNull] ObjCParser.Abstract_declarator_suffixContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.class_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_list([NotNull] ObjCParser.Class_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.class_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_list([NotNull] ObjCParser.Class_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.property_synthesize_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_synthesize_item([NotNull] ObjCParser.Property_synthesize_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.property_synthesize_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_synthesize_item([NotNull] ObjCParser.Property_synthesize_itemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.direct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirect_declarator([NotNull] ObjCParser.Direct_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.direct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirect_declarator([NotNull] ObjCParser.Direct_declaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.implementation_definition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementation_definition_list([NotNull] ObjCParser.Implementation_definition_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.implementation_definition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementation_definition_list([NotNull] ObjCParser.Implementation_definition_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_expression([NotNull] ObjCParser.And_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_expression([NotNull] ObjCParser.And_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.superclass_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperclass_name([NotNull] ObjCParser.Superclass_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.superclass_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperclass_name([NotNull] ObjCParser.Superclass_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.catch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatch_statement([NotNull] ObjCParser.Catch_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.catch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatch_statement([NotNull] ObjCParser.Catch_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.dictionary_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionary_pair([NotNull] ObjCParser.Dictionary_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.dictionary_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionary_pair([NotNull] ObjCParser.Dictionary_pairContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_specifier([NotNull] ObjCParser.Type_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_specifier([NotNull] ObjCParser.Type_specifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.selector_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector_expression([NotNull] ObjCParser.Selector_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.selector_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector_expression([NotNull] ObjCParser.Selector_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ObjCParser.declarator_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator_suffix([NotNull] ObjCParser.Declarator_suffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ObjCParser.declarator_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator_suffix([NotNull] ObjCParser.Declarator_suffixContext context);
}
